### PR TITLE
removing const loop iterations

### PR DESCRIPTION
**Pull request by gustavofp**
Pull request for this issue #47

### CODE REVIEW

**Comment by ataillefer** [comment]
Thanks, we'll have a look soon.

**Comment by gustavofp** [comment]
Any news guys? 
Sorry for asking, but we need to fix this problem to deploy a release.

**Comment by ataillefer** [comment]
Created https://jira.nuxeo.com/browse/NXJS-129 in our issue management tool.
Yet, before fixing it and releasing a new version of the client we need to discuss internally if the client is ready for a new release and freeze its scope, we might want to add a few things in this next release.

Let's wait Monday for the lead developer to come back and address this issue.

**Comment by troger** [comment]
Thanks @gustavofp for your PR! It has been merged in 04b00aa.

I will trigger a patch release.

**Pull request closed without merging**
